 const actionType = {
    GENERIC_MESSAGE: 'GENERIC_MESSAGE',
    HEARTBEAT: 'HEARTBEAT',
    JOIN_IRC_CHANNEL: 'JOIN_IRC_CHANNEL',
    IRC_PM_RECEIVED: 'IRC_PM_RECEIVED',
    IRC_MESSAGE_RECEIVED: 'IRC_MESSAGE_RECEIVED'
}

module.exports = { actionType }